[project]
name = "ai-study"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=5.44.1",
    "langchain>=0.3.27",
    "langchain-community>=0.3.29",
    "openai>=1.106.1",
]
